[package]
name = "base58-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-base58 = "0.0.4"
hex = "0.4.3"
solana-sdk = "1.9.1"